name: collaboration-service
services:
  server:
    build:
      context: .
      args:
        EXPRESS_PORT: ${EXPRESS_PORT}
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/peerprep-collaboration"
      EXPRESS_PORT: ${EXPRESS_PORT}

  mongodb:
    image: mongo:8.2.6-rc0
    ports:
      - 27117:27017
    volumes:
      - ./data/mongodb:/data/db
