name: collaboration-service

services:
  collaboration-server:
    build:
      context: .
      args:
        EXPRESS_PORT: 3003
    ports:
      - 3003:3003
    depends_on:
      - redis
    environment:
      QUESTION_API_BASE_URL: http://question-service:3002
      REDIS_URL: "redis://redis:6379"
      EXPRESS_PORT: 3003
      NODE_ENV: production
    networks:
      - peerprep-network
    restart: always

  redis:
    image: redis:8.2.1-alpine
    ports:
      - 6380:6379
    restart: always
    networks:
      - peerprep-network

networks:
  peerprep-network:
    external: true